### ISSUE TITLE
please make the functions/objects params to be detectable by pylance

### ISSUE THREAD

**Issue by WeiNyn** [pynecone-io/pynecone#54] opened 2022-12-10 13:05 UTC

**Comment by frankdevans** [comment] 2022-12-10 16:33
If I can (especially if I can help), I would like to second this for Pyright.

**Comment by Alek99** [comment] 2022-12-10 20:49
Ok thanks for pointing this out I haven't used Pylance personally, so if @frankdevans you want to try this go ahead and give it a shot for Pylance/Pyright, that would be really helpful. No worries if not I can look and to this an start implementing it soon

**Comment by Alek99** [comment] 2023-02-02 02:00
Just following up on this issue, any luck with this or I can open it up to the rest of the open source

**Comment by picklelo** [comment] 2023-02-04 23:33
Duplicate of #355

**Closed by picklelo** 2023-02-04 23:33 UTC
Labels: enhancement
