### ISSUE TITLE
Build error during "pc run --env prod"

### ISSUE THREAD

**Issue by wbfw109** [pynecone-io/pynecone#292] opened 2023-01-20 08:36 UTC
**Describe the bug**
I don't know what's problem. Running in development works well (```pc run```). but in production not. (```pc run --env prod``` )

**To Reproduce**
- My pcconfig.py
```
config = pc.Config(
    app_name="glossary_app",
    api_url="192.168.0.4:8000",
    bun_path="$HOME/.bun/bin/bun",
    db_url="sqlite:///pynecone.db",
)
```
- and run ```pc run --env prod``` in fish shell

**Expected behavior**
Server will be opend.

**Screenshots**
![image](https://user-images.githubusercontent.com/37881026/213651679-dfc79fe9-35ef-454e-b31b-7bcad7645160.png)

**Specifics (please complete the following information):**
 - Python Version: 3.11.0
 - Pynecone Version: pynecone-io = "^0.1.12"
 - OS: WSL Ubuntu 22.04 distribution in Windows 11 Version 21H2 (OS Build 22000. 1455)
 - Browser (Optional): Edge Browser
 - Shell: Fish shell

**Additional context**
After the error occurs, port 8000 always in used. It is recreated with new PID even if I kill it's PID.
└ This only seems to happen when I exit VS code with server is opening. 📅 updated on 2023-01-21 10:00:04

**Comment by Alek99** [comment] 2023-01-20 23:40
Ok interesting I haven't experienced this error before but I'll try and recreate. Just to make sure your local host 3000 is not working right is it just a blank page?

**Comment by wbfw109** [comment] 2023-01-21 01:04
Yes. the error output is same even if the page is empty. ( def index() returns pc.text("testing...") )

**Comment by dev-onejun** [comment] 2023-01-21 01:26
I'm sorry to bother you, but ..

__did you install node version more than `12.22.0`?__

It seems that all the errors are related to node.

**Comment by wbfw109** [comment] 2023-01-21 01:52
> I'm sorry to bother you, but ..
> 
> **did you install node version more than `12.22.0`?**
> 
> It seems that all the errors are related to node.

My node version is v18.12.1 (installed from nvm)

**Comment by dev-onejun** [comment] 2023-01-22 03:17
note: I failed to regenerate to make the issue.

The following environments are that I tried.

1. ubuntu 22.04.01 / python 3.11.0rc1 / node 18.12.1 with nvm / pynecone-io 0.1.13 / Fish shell

2. Windows 10 WSL ubuntu 22.04.01 / python 3.11.0rc1 / node 18.12.1 with nvm / pynecone-io 0.1.13 / Fish shell

**Comment by Alek99** [comment] 2023-01-22 03:51
@dev-onejun Thank for trying to reproduce. I can't reproduce this either, mine seems to work alright. If anyone else gets this issue I'll look into it more. Sorry for this issue @wbfw109 maybe it will be resolved in newer future versions can't seem to pin this error as of now

**Comment by wbfw109** [comment] 2023-01-25 09:53
> @dev-onejun Thanks for trying to reproduce. I can't reproduce this either, mine seems to work alright. If anyone else gets this issue I'll look into it more. Sorry for this issue @wbfw109 maybe it will be resolved in newer future versions can't seem to pin this error as of now

I solved. (but I don't know exact reason)

**List of what I did:**
- remove Pynecone previous version and install pre-release version = "0.1.13" in poetry.
- ```Shell:pwsh> Get-Service LxssManager | Restart-Service``` ([WSL2 connect bug](https://github.com/microsoft/WSL/issues/5018))  
  and restart computer


pyconfig.py:
```
config = pc.Config(
    app_name="glossary_app",
    api_url="http://localhost:8000",
    bun_path="$HOME/.bun/bin/bun",
    db_url="sqlite:///pynecone.db",
)
```
and run (I ignore the eslint installation error.)
![pynecone-io-0 1 13v_2](https://user-images.githubusercontent.com/37881026/214531293-060920d1-0ff4-4cbc-9cc5-568bb205947b.png)

I carefully guess that it was a problem with the version of Pynecone.

Thank you all for your interest in this issue. :)
If there are no problems for a while, I will close this issue.

**Closed** 2023-01-25 12:51 UTC
Labels: bug
