### ISSUE TITLE
forms - input page's example is too slow

### ISSUE THREAD

**Issue by LayGPark** [pynecone-io/pynecone#1137] opened 2023-06-05 06:39 UTC
**Describe the bug**
https://pynecone.io/docs/library/forms/input
exaples in this page are too slow.

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version:
 - Pynecone Version:
 - OS: Mac
 - Browser (Optional): whale(Chromium base), safari
 
**Additional context**

**Comment by masenf** [comment] 2023-06-05 07:33
Likely dupe of #671

In the current implementation, nearly _all_ interactions have a roundtrip to the backend over the websocket. If you have low latency to the backend server, usually this isn't too much of a problem, but the further away you get, the more noticable it is.

A nice interim solution is the form submit functionality, which allows you to populate the page with uncontrolled inputs, and then recieve all of the form fields as a dict in one roundtrip to the backend; this is more like a traditional form-post, but with validation baked into the client side controls.

To test, is [the first example on this page](https://pynecone.io/docs/library/forms/form) slow? That's using uncontrolled inputs with a single on_submit event. The on_submit might be slow, but typing in the form, etc should not be lagging.

**Comment by LayGPark** [comment] 2023-06-07 06:20
@masenf 
> To test, is [the first example on this page](https://pynecone.io/docs/library/forms/form) slow? That's using uncontrolled inputs with a single on_submit event. The on_submit might be slow, but typing in the form, etc should not be lagging.
No, first example is not slow. 
Thank you for your explain.
Form submit is better for me. :)

**Closed** 2023-06-07 06:20 UTC
