### ISSUE TITLE
F-Strings don't render Images with remote URLs

### ISSUE THREAD

**Issue by LaxmanSinghTomar** [pynecone-io/pynecone#706] opened 2023-03-19 05:35 UTC
**Describe the bug**
Images are rendered incorrectly when the URL is passed via State Vars within f-strings.

**To Reproduce**
 - Code/Link to Repo:
    ```pc.text(f"https://logo.clearbit.com/${State.news_publisher_domain[pos]}"),```
    ```pc.image(src=f"https://logo.clearbit.com/${State.news_publisher_domain[pos]}")```

**Expected behavior**
Images hosted should be displayed.

**Screenshots**
![logo](https://user-images.githubusercontent.com/37807897/226155804-cff314f5-f872-4465-b86b-accdb855eec9.png)

**Specifics (please complete the following information):**
 - Python Version: 3.10
 - Pynecone Version: 0.1.20
 - OS: Ubuntu 20.04
 - Browser (Optional): Chrome Version 110.0.5481.177 (Official Build) (64-bit)
 
**Additional context**
Works correctly when the URL is hardcoded.

**Comment by picklelo** [comment] 2023-04-03 17:17
Duplicate of #707

**Closed by picklelo** 2023-04-03 17:17 UTC
Labels: bug
