### ISSUE TITLE
Can you please add an 'Autocomplete' component?

### ISSUE THREAD

**Issue by heumsi** [pynecone-io/pynecone#345] opened 2023-01-26 04:39 UTC
**Describe the bug**

I know there is no "Autocomplete" component by default in Chakra UI.

However, I can add an Autocomplete component through the library below.

https://github.com/koolamusic/chakra-ui-autocomplete

Could you possibly support this component in Pynecone?

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version:
 - Pynecone Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by Alek99** [comment] 2023-01-26 07:51
Yes I think we need to update our chakra version but we can add this

**Comment by masenf** [comment] 2023-07-06 23:13
Duplicate of #239

**Closed by masenf** 2023-07-06 23:13 UTC
Labels: help wanted, feature request
