### ISSUE TITLE
Make methods in state.py private

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#834] opened 2023-04-17 23:20 UTC
Currently some methods in the `State` class are not private, and it prevents us from adding event handlers with certain names. For example, you cannot add an event handler names `process`, `preprocess`, or `postprocess`. We should convert the methods to be e.g. `_process`

**Comment by tauseefmohammed2** [comment] 2023-04-18 02:39
Hi!
I would love to contribute to the repo. I saw that the issue is labelled "first time", which is perfect for me as I am new to this project and eager to get started. Could you please assign this issue to me?

**Comment by sampanacharya** [comment] 2023-04-18 12:51
Hi @picklelo 
I was reviewing the code for this issue, there is a method in the `State` class  named as `convert_handlers_to_fns` should this also get converted to `__convert_handlers_to_fns`?

**Comment by picklelo** [comment] 2023-04-18 18:35
@tauseefmohammed2 done! Feel free to post here or in our Discord if you need help. The main idea is all the builtin methods in `state.py` should be prefixed with `_` so event handlers defined later won't override them.

**Closed** 2023-04-24 17:45 UTC
Labels: enhancement, good first issue
