### ISSUE TITLE
Error since I updated to 0.1.10: React does not recognize the `hasStriped` prop on a DOM element

### ISSUE THREAD

**Issue by matt-grain** [pynecone-io/pynecone#122] opened 2022-12-16 19:35 UTC
Hi,

I updated today my project from 0.1.8 to 0.1.10 and now I have this error but I don't understand where it comes from

````
event - compiled client and server successfully in 236 ms (868 modules)
Warning: React does not recognize the `hasStriped` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `hasstriped` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at /home/matt/projects/git/pynecone/app/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at Progress (/home/matt/projects/git/pynecone/app/.web/node_modules/@chakra-ui/progress/dist/chakra-ui-progress.cjs.dev.js:355:34)
    at div
    at /home/matt/projects/git/pynecone/app/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at /home/matt/projects/git/pynecone/app/.web/node_modules/@chakra-ui/layout/dist/chakra-ui-layout.cjs.dev.js:910:24
    at VStack
    at div
    at /home/matt/projects/git/pynecone/app/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at /home/matt/projects/git/pynecone/app/.web/node_modules/@chakra-ui/layout/dist/chakra-ui-layout.cjs.dev.js:910:24
    at VStack
    at div
    at /home/matt/projects/git/pynecone/app/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at Component (webpack-internal:///./pages/verra.js:30:96)
    at EnvironmentProvider (/home/matt/projects/git/pynecone/app/.web/node_modules/@chakra-ui/react-env/dist/chakra-ui-react-env.cjs.dev.js:120:24)
    at ColorModeProvider (/home/matt/projects/git/pynecone/app/.web/node_modules/@chakra-ui/color-mode/dist/chakra-ui-color-mode.cjs.dev.js:228:21)
    at ThemeProvider (/home/matt/projects/git/pynecone/app/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:106:21)
    at ThemeProvider (/home/matt/projects/git/pynecone/app/.web/node_modules/@chakra-ui/system/dist/chakra-ui-system.cjs.dev.js:57:27)
    at /home/matt/projects/git/pynecone/app/.web/node_modules/@chakra-ui/hooks/dist/chakra-ui-hooks.cjs.dev.js:265:23
    at /home/matt/projects/git/pynecone/app/.web/node_modules/@chakra-ui/hooks/dist/chakra-ui-hooks.cjs.dev.js:265:23
    at ChakraProvider (/home/matt/projects/git/pynecone/app/.web/node_modules/@chakra-ui/provider/dist/chakra-ui-provider.cjs.dev.js:40:24)
    at MyApp (webpack-internal:///./pages/_app.js:22:18)
    at StyleRegistry (/home/matt/projects/git/pynecone/app/.web/node_modules/styled-jsx/dist/index/index.js:448:36)
    at AppContainer (/home/matt/projects/git/pynecone/app/.web/node_modules/next/dist/server/render.js:298:29)
    at AppContainerWithIsomorphicFiberStructure (/home/matt/projects/git/pynecone/app/.web/node_modules/next/dist/server/render.js:327:57)
    at div
    at Body (/home/matt/projects/git/pynecone/app/.web/node_modules/next/dist/server/render.js:614:21)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
````

Any hint on how to debug it ?

Thanks !

**Comment by Alek99** [comment] 2022-12-16 19:48
@matt-grain Hi is this when you just update your current project creating a new project doesn't have this issue right

**Comment by Alek99** [comment] 2022-12-16 19:49
Maybe `pc init` and `pc run` the project on 0.1.10

**Comment by matt-grain** [comment] 2022-12-16 19:51
Yeah this is what I thought, I tried that but still here. So I'll recreate a project from scratch! No issue

**Comment by Alek99** [comment] 2022-12-16 19:53
Actually you delete your `.web` folder and pc init and then pc run you maybe be ok in your same project,  if that doesn't work maybe recreate.

**Comment by matt-grain** [comment] 2022-12-16 19:57
I tried that too. Not better. Let me try to recreate it right now.

**Comment by matt-grain** [comment] 2022-12-16 20:08
So even with a new project, the same error appears

**Comment by Alek99** [comment] 2022-12-16 20:11
Are you using has_striped anywhere or can you paste some of your code

**Comment by matt-grain** [comment] 2022-12-16 20:18
No has_stripped..

Here is my code:
````python
"""Welcome to Pynecone! This file outlines the steps to create a basic app."""
from typing import List, Any, Optional, Dict
import pynecone as pc

from app_v2.orchestrator import Orchestrator

from dotenv import load_dotenv
from loguru import logger


load_dotenv()

question_style = {
    "bg": "white",
    "padding": "2em",
    "border_radius": "25px",
    "w": "50em",
    "align_items": "left",
}

# fmt: off
section_style = {
    "bg": "white",
    "padding": "1.20em",
    "paddingTop": "1.9em",
    "paddingRight": "1.5em",
    "border_radius": "25px",
    "w": "1em",
    "h": "100%",
    "align_items": "center",
    "align": "center",
    "fontWeight": "bold",
    "vertical_align": "middle",
    "fontSize": "large",
    # "text_transform": "rotate(90deg)"
}

orchestrator : Orchestrator

methodologies: Dict[str, Dict] = {
    "C1": {
        "desc": "Q1",
        "icon": "logo1.jpeg"
    },
    "C2": {
        "desc": "Q2",
        "icon": "logo2.jpeg"
    }  
}


class QuestionModel(pc.Model, table=False):

    title: str
    description: str
    question_nb: int
    question_type: str
    answer: Optional[str]
    tooltip: Optional[str]
    possible_answers: List[Dict]
    section: str
    kb_link: str


class AppState(pc.State):
    """The app state."""

    certifier: str
    methodology: str
    icon: str
    questions: List = []
    started: bool = False
    is_invalid: bool = False
    done: bool = False
    answers_list: List[List[str]] = [[]]

    def set_certifier(self, certifier: str):

        global orchestrator

        # cleaning
        self.questions.clear()
        self.answers_list.clear()
        self.started = False
        self.done = False

        logger.debug(f"Setting certifier: {certifier}")
        self.certifier = certifier
        self.methodology = methodologies[certifier]['desc']
        self.icon = methodologies[certifier]['icon']
        orchestrator = Orchestrator(certifier=certifier)


    def set_answer(self, answer: str, index: int):
        for answer in self.questions[index].possible_answers:
            if answer["answer_value"] == answer:
                self.questions[index].answer = answer
                logger.debug(f"Record answer {answer} for Question {self.questions[index].id}")

    @pc.var
    def get_current_question_id(self) -> int:

        if len(self.questions) == 0:
            return 0
        else:
            return self.questions[-1].id

    @pc.var
    def get_questions(self) -> List[QuestionModel]:
        return self.questions


class SubmitButtonState(AppState):

    def start(self):

        # init project
        section, question, status = orchestrator.start()

        logger.debug(f"1st Question: {question}")

        title = f"{question['section'].replace('_', ' ')} section"

        first_question = QuestionModel(
            id=0,
            question_nb=question["question_nb"],
            title=title,
            tooltip="" if question["tooltip"] is None else question["tooltip"],
            description=question["title"],
            possible_answers=question["possible_answers"],
            section=question["section"],
            question_type=question["question_type"],
            kb_link="" if question["kb_link"] is None else question["kb_link"],
        )

        self.questions.append(first_question)
        self.answers_list = [[str(answer['answer_value']) for answer in question["possible_answers"]]]

        logger.debug(self.questions)
        logger.debug(self.answers_list)

        self.started = True

    def submit(self):

        if self.questions[-1].answer is None and self.questions[-1].question_type != "instruction":
            self.is_invalid = True

        else:
            self.is_invalid = False

            answer_id = None
            answer = None

            if self.questions[-1].question_type == "instruction":
                answer_id = self.questions[-1].possible_answers[0]["answer_id"]

            elif self.questions[-1].question_type in ["binary", "choice"]:
                answer_id = self.questions[-1].answer["answer_id"]
                answer = self.questions[-1].answer["answer_value"]

            else:
                answer_id = self.questions[-1].possible_answers[0]["answer_id"]
                answer = self.questions[-1].answer

            if answer_id is None:
                raise Exception(f"Could not find answer for value {self.questions[-1].answer}")

            answer_dict = {"answer_id": answer_id, "answer_value": answer}

            question_dict = {"section": self.questions[-1].section, "question_nb": self.questions[-1].question_nb}

            section, question, assessment_status = orchestrator.set_answer(question=question_dict, answer=answer_dict)

            if question is not None:

                logger.debug(f"Next question: {question}")

                title = f"{question['section'].replace('_', ' ')} section"
                next_question = QuestionModel(
                    id=len(self.questions),
                    question_nb=question["question_nb"],
                    title=title,
                    tooltip="" if question["tooltip"] is None else question["tooltip"],
                    description=question["title"],
                    possible_answers=question["possible_answers"],
                    section=question["section"],
                    question_type=question["question_type"],
                    kb_link="" if question["kb_link"] is None else question["kb_link"],
                )

                self.questions.append(next_question)
                self.answers_list = self.answers_list + [[str(answer['answer_value']) for answer in question["possible_answers"]]]

                logger.debug(next_question)
                logger.debug(self.answers_list)
            
            else:
                if assessment_status == "failure":
                    failure = QuestionModel(
                        id=len(self.questions),
                        question_nb=-1,
                        title="Ohhhh you failed :(",
                        tooltip="",
                        description="really sorry about that. Kidding :)",
                        possible_answers=[],
                        section="End of questionnaire",
                        question_type="instruction",
                        kb_link="",
                    )                
                    self.questions.append(failure)
                    self.done = True

                elif assessment_status == "success":
                    success = QuestionModel(
                        id=len(self.questions),
                        question_nb=-1,
                        title="Yahooo you won !!!!",
                        tooltip="",
                        description="You did it !!! :)",
                        possible_answers=[],
                        section="End of questionnaire",
                        question_type="instruction",
                        kb_link="",
                    )                
                    self.questions.append(success)
                    self.done = True


    def back(self):
        if len(self.questions) > 1:
            orchestrator.rollback(self.questions[-2].section, self.questions[-2].question_nb)
            self.questions.pop()
            self.answers_list.pop()
            self.done = False

    def restart(self):
        self.questions.clear()
        self.answers_list.clear()
        self.started = False
        self.done = False

    def results(self):
        for q in self.questions:
            logger.debug(q)


class SliderState(AppState):
    value: int = 0

    def set_value(self, value: int):
        logger.debug(f"Set value from slider: {value}")
        self.value = value

        # not sure why it doesn't work as expected
        # super().set_answer(str(value))
        logger.debug(f"Record answer for Question {self.questions[len(self.questions)-1].question_nb}")
        self.questions[len(self.questions) - 1].answer = str(value)


class InputState(AppState):

    def set_answer(self, freetext: str, index: int):
        
        answer = self.questions[index].possible_answers[0]
        answer["answer_value"] = freetext
        self.questions[index].answer = answer
        logger.debug(f"Record answer {freetext} for Question {self.questions[index].id}")

class RadioState(AppState):

    def set_choice(self, choice, index):

        for answer in self.questions[index].possible_answers:
            if answer["answer_value"] == choice:
                self.questions[index].answer = answer
                logger.debug(f"Record answer {answer} for Question {self.questions[index].id}")

class ButtonState(AppState):

    button_state: Dict[int, str] = {}
    translated_vals = {"yes": ["yes", "true", "y"], "no": ["no", "false", "n"]}

    def switch(self, idx: int, state: bool):

        logger.debug(f"Setting state for {idx} in {self.button_state}")
        self.button_state[idx] = "yes" if state else "no"

        self.button_state = self.button_state
        logger.debug(f"Button states: {self.button_state}")

        for answer in self.questions[idx].possible_answers:
            if answer["answer_value"].lower() in self.translated_vals[self.button_state[idx]]:
                self.questions[idx].answer = answer
                logger.debug(f"Record answer {self.button_state[idx]} for Question {self.questions[idx].id}")


class DrawerState(AppState):
    show_right: bool = False
    show_top: bool = False

    def top(self):
        self.show_top = not (self.show_top)

    def right(self):
        self.show_right = not (self.show_right)


def questionnaire():

    return pc.center(
        pc.vstack(
            pc.flex(
                pc.center(),
                pc.spacer(),
                pc.center(
                    pc.breadcrumb(
                        pc.breadcrumb_item(pc.breadcrumb_link("Home", href="/")),
                        pc.breadcrumb_item(pc.breadcrumb_link("Q1", href="/questionnaire"), on_click=lambda: AppState.set_certifier("1")),
                        pc.breadcrumb_item(pc.breadcrumb_link("Q2", href="/questionnaire"), on_click=lambda: AppState.set_certifier("2")),
                    ),
                ),
                pc.spacer(),
                pc.center(
                    pc.avatar(size="sm"),
                ),
                width="95%",
            ),
            header(),
            pc.foreach(AppState.get_questions, lambda a_question: question_component(details=a_question)),
            pc.vstack(
                pc.progress(
                    value=AppState.get_current_question_id / 5 * 100,
                    width="100%",
                    height="1.3em",
                    border_radius="25px",
                    bg="lightblue",
                    is_animated=True,
                    has_striped=True,
                    is_indeterminate=AppState.started == False,
                ),
                spacing="1em",
                min_width=["10em", "40em"],
            ),
            pc.vstack(
                pc.cond(
                    AppState.started == True,
                    pc.button_group(
                        pc.button(
                            "Restart",
                            bg="black",
                            color="white",
                            width="6em",
                            padding="1em",
                            on_click=SubmitButtonState.restart,
                        ),
                        pc.button(
                            "Back",
                            bg="black",
                            color="white",
                            width="6em",
                            padding="1em",
                            on_click=SubmitButtonState.back,
                        ),
                        pc.button(
                            "Next",
                            bg="black",
                            color="white",
                            width="6em",
                            padding="1em",
                            on_click=SubmitButtonState.submit,
                            is_disabled=AppState.done,
                        ),
                        pc.button(
                            "Results",
                            bg="black",
                            color="white",
                            width="6em",
                            padding="1em",
                            on_click=SubmitButtonState.results,
                        ),
                    ),
                    pc.button(
                        "Start",
                        bg="black",
                        color="white",
                        width="6em",
                        padding="1em",
                        on_click=SubmitButtonState.start,
                    ),
                ),
                padding_y="2em",
            ),
            spacing="1em",
        ),
        padding_y="2em",
        height="100vh",
        align_items="top",
        bg="#ededed",
        overflow="auto",
    )


def header():

    return pc.hstack(
        pc.box("", style=section_style),
        pc.vstack(
            pc.heading("Questionnaire for " + AppState.methodology),
            pc.divider(),
            pc.hstack(pc.text("Welcome to our test questionnaire!"), pc.image(src=AppState.icon, width="auto", height="6em"), justify="center"),
            style=question_style,
        ),
    )


def question_component(details: QuestionModel):

    return pc.hstack(
        pc.box(details.id, style=section_style),
        pc.vstack(
            pc.heading(details.title, size="md"),
            pc.text(details.description),
            pc.divider(),
            pc.cond(details.question_type == "binary", c_button(details)),
            pc.cond(details.question_type == "freetext", c_input(details)),
            pc.cond(details.question_type == "slider", c_slider(details)),
            # pc.cond(details.question_type == "instruction", c_instruction(details)),
            pc.cond(details.question_type == "choice", c_choice(details)),
            pc.hstack(
                pc.tooltip(
                    pc.cond(
                        details.kb_link != "",
                        pc.icon(tag="InfoOutlineIcon", color="black"),
                    ),
                    label=details.tooltip,
                ),
                pc.cond(
                    details.kb_link != "",
                    pc.text("Click for more info!", as_="i", on_click=DrawerState.right),
                ),
                pc.cond(
                    details.kb_link != "",
                    pc.drawer(
                        pc.drawer_overlay(
                            pc.drawer_content(
                                pc.drawer_header("GRAIN wiki"),
                                pc.drawer_body("Here the wiki content"),
                                pc.drawer_footer(pc.button("Close", on_click=DrawerState.right)),
                            )
                        ),
                        is_open=DrawerState.show_right,
                    ),
                ),
            ),
            style=question_style,
        ),
    )


def c_button(details: QuestionModel):

    button_style = {
        "color": "black",
        "background": "lightblue",
        "_hover": {
            "background": "lightblue",
            "color": "black",
        },
        "_active": {
            "background": "red",
            "color": "white",
        },
    }

    return pc.form_control(
        pc.button_group(
            pc.button(
                "yes",
                size="lg",
                on_click=lambda: ButtonState.switch(details.id, True),
                is_active=ButtonState.button_state[details.id]=="yes",
                style=button_style,
                is_disabled=AppState.get_current_question_id != details.id,
            ),
            pc.button(
                "no",
                size="lg",
                on_click=lambda: ButtonState.switch(details.id, False),
                is_active=ButtonState.button_state[details.id]=="no",
                style=button_style,
                is_disabled=AppState.get_current_question_id != details.id,
            ),
            is_required=True,
        )
    )


def c_input(details: QuestionModel):
    return pc.form_control(
        pc.input(on_change=lambda answer: InputState.set_answer(answer, details.id), is_disabled=AppState.get_current_question_id != details.id, is_invalid=AppState.is_invalid),
        is_required=True,
    )


def c_choice(details: QuestionModel):
    return pc.hstack(
        pc.form_control(
            pc.radio_group(
                pc.foreach(AppState.answers_list[details.id], lambda answer: c_radio(answer)),
                on_change=lambda choice: RadioState.set_choice(choice, details.id)
            ),
            is_required=True,
        )
    )

def c_radio(answer: str):
    return pc.flex(
        pc.radio(answer, is_checked=True, is_disabled=False),
        pc.spacer(),
        align_items="Left"
    )


def c_slider(details: QuestionModel):
    return pc.vstack(
        pc.form_control(
            pc.text(SliderState.value),
            pc.slider(
                value=SliderState.value,
                on_change=SliderState.set_value,
                min_=0,
                max_=60,
                default_value=0,
                is_disabled=AppState.get_current_question_id != details.id,
                is_invalid=AppState.is_invalid,
            ),
            is_required=True,
        )
    )


def index():
    return pc.center(
        pc.vstack(
            pc.heading("Welcome to our demo tool!", font_size="2em"),
            pc.box("Get started with a questionnaire"),
            pc.hstack(
                pc.link(
                    pc.image(src="/logo.jpeg", width="auto", height="3em"),
                    href="/questionnaire",
                    border="0.1em solid",
                    padding="0.5em",
                    border_radius="0.5em",
                    _hover={
                        "color": "rgb(107,99,246)",
                    },
                    on_click=lambda: AppState.set_certifier("C1")
                ),
                pc.link(
                    pc.image(src="/logo.jpeg", width="auto", height="3em", align="center"),
                    href="/questionnaire",
                    border="0.1em solid",
                    padding="0.5em",
                    border_radius="0.5em",
                    _hover={
                        "color": "rgb(107,99,246)",
                    },
                    on_click=lambda: AppState.set_certifier("C2")
                ),
                spacing="2em",
            ),
            spacing="1.5em",
            font_size="2em",
        ),
        padding_top="10%",
    )


# style = {
#     pc.Code: {
#         "color": "white",
#         "background_color": "red",
#         "active": "green",
#         "selected": "green",

#     },
# }

# Add state and page to the app.
app = pc.App(state=AppState)  # , style=style)
app.add_page(index, path="/", title="Demo tool")
app.add_page(questionnaire, path="/questionnaire", title="questionnaire")
app.compile()


````

**Comment by Alek99** [comment] 2022-12-16 20:20
Ok I'll try and debug this in the meantime maybe go back to the last release and continue your development. Thanks for pointing this out

**Comment by matt-grain** [comment] 2022-12-16 20:21
This error is not fatal, appears in the logs and browser console but doesn't prevent the application to run. So nothing critical :)

**Comment by matt-grain** [comment] 2022-12-17 13:24
Ah you were right, it was the progress bar:

````python
            pc.vstack(
                pc.progress(
                    value=AppState.get_current_question_id / 5 * 100,
                    width="100%",
                    height="1.3em",
                    border_radius="25px",
                    bg="lightblue",
                    is_animated=True,
                    has_striped=True,
                    is_indeterminate=AppState.started == False,
                ),
                spacing="1em",
                min_width=["10em", "40em"],
            ),
````

I removed has_striped and no error anymore

**Comment by Alek99** [comment] 2022-12-18 02:37
Try has_stripe not has_striped

**Comment by Alek99** [comment] 2022-12-18 02:38
Ill update the docs

**Comment by matt-grain** [comment] 2022-12-18 02:47
ah better. But... what `has_stripe` should do? I don`t see the difference

**Comment by Alek99** [comment] 2022-12-18 03:13
It should make the progress bar stripped Ill update this component so in the next release it works as intended

**Comment by Alek99** [comment] 2022-12-22 01:42
Added this issue in this pr should be fixed on the next release https://github.com/pynecone-io/pynecone/pull/159

**Closed by Alek99** 2022-12-22 01:42 UTC
Labels: bug
