### ISSUE TITLE
env mode in rx.Config is ignored when defined in rxconfig.py

### ISSUE THREAD

**Issue by Lendemor** [pynecone-io/pynecone#1311] opened 2023-07-06 21:14 UTC
**Describe the bug**
While redeploying my website, I noticed that if you define `env` inside rx.Config, it will get ignored and always run dev mode by default.
The same `env` parameter is working when used from command line with `--env prod`

**To Reproduce**
Create any repo and change the  `env` in config 

**Expected behavior**
`reflex run` should respect all parameters of the config, no matter the source.

**Specifics (please complete the following information):**
 - Python Version: 3.10.6
 - Reflex Version: 0.2.0
 - OS: Ubuntu  22.04

**Comment by masenf** [comment] 2023-07-06 22:58
Duplicate of #1254

**Closed by masenf** 2023-07-06 22:58 UTC
Labels: bug
